version: "3"

services:
  cable:
    depends_on:
      - "redis"
    build: .
    command: puma -p 28080 cable/config.ru
    ports:
      - "28080:28080"
    volumes:
      - ".:/app"
    env_file:
      - ".env.docker"

  postgres:
    image: "postgres:10-alpine"
    environment:
      POSTGRES_USER: "mdb"
      POSTGRES_PASSWORD: "yourpassword"
    ports:
      - "5432:5432"
    volumes:
      - "postgres:/var/lib/postgresql/data"

  redis:
    image: "redis:3.2-alpine"
    command: redis-server --requirepass yourpassword
    ports:
      - "6379:6379"
    volumes:
      - "redis:/data"
    sysctls:
      # https://github.com/docker-library/redis/issues/35
      net.core.somaxconn: "511"

  sidekiq:
    depends_on:
      - "postgres"
      - "redis"
    build: .
    command: sidekiq -C config/sidekiq.yml.erb
    volumes:
      - ".:/app"
    env_file:
      - ".env.docker"

  web:
    depends_on:
      - "postgres"
      - "redis"
      - "webpack"
    build: .
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - ".:/app"
    env_file:
      - ".env.docker"

  webpack:
    build: .
    env_file:
      - ".env.docker"
    command: ./bin/webpack-dev-server
    volumes:
      - ".:/app"
    ports:
      - "3035:3035"

volumes:
  redis:
  postgres:
  web:
  webpack:
